### ISSUE TITLE
RequestError [HttpError]: Resource not accessible by integration

### ISSUE THREAD

**Issue by bukharim96** [gr2m/octokit-plugin-create-pull-request#29]
I used this in one of my GitHub actions and it failed with the following error:

```
RequestError [HttpError]: Resource not accessible by integration
    at /home/runner/work/blogg-template/blogg-template/node_modules/@octokit/request/dist-node/index.js:66:23
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async createPullRequest (/home/runner/work/blogg-template/blogg-template/node_modules/octokit-create-pull-request/lib/create-pull-request.js:23:18) {
  name: 'HttpError',
  status: 403,
  headers: {
    'access-control-allow-origin': '*',
    'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset',
    connection: 'close',
    'content-encoding': 'gzip',
    'content-security-policy': "default-src 'none'",
    'content-type': 'application/json; charset=utf-8',
    date: 'Thu, 02 Apr 2020 23:24:52 GMT',
    'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
    server: 'GitHub.com',
    status: '403 Forbidden',
    'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
    'transfer-encoding': 'chunked',
    vary: 'Accept-Encoding, Accept, X-Requested-With',
    'x-content-type-options': 'nosniff',
    'x-frame-options': 'deny',
    'x-github-media-type': 'github.v3; format=json',
    'x-github-request-id': '0404:3924:66ACE:F1476:5E867444',
    'x-ratelimit-limit': '1000',
    'x-ratelimit-remaining': '997',
    'x-ratelimit-reset': '1585873490',
    'x-xss-protection': '1; mode=block'
  },
  request: {
    method: 'GET',
    url: 'https://api.github.com/user',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'octokit.js/16.43.1 Node.js/12.13.1 (Linux 5.0; x64)',
      authorization: 'token [REDACTED]'
    },
    request: { hook: [Function: bound bound register] }
  },
  documentation_url: 'https://developer.github.com/v3/users/#get-the-authenticated-user'
}
```

Any idea what the issue might be? Thanks.

**Comment by gr2m** [comment]
Looks like the request causing the error is `GET /user`, which is not an endpoint used by this plugin. A GitHub Action cannot access the `GET /user` endpoint, it requires an authentication bound to a user

**Comment by bukharim96** [comment]
I added a new token with `user` access and it solved that issue. However, a new `422` issue came up:

```
RequestError [HttpError]: Reference already exists
    at /home/runner/work/blogg-template/blogg-template/node_modules/@octokit/request/dist-node/index.js:66:23
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async createPullRequest (/home/runner/work/blogg-template/blogg-template/node_modules/octokit-create-pull-request/lib/create-pull-request.js:103:3) {
  name: 'HttpError',
  status: 422,
  headers: {
    'access-control-allow-origin': '*',
    'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset',
    connection: 'close',
    'content-length': '121',
    'content-security-policy': "default-src 'none'",
    'content-type': 'application/json; charset=utf-8',
    date: 'Fri, 03 Apr 2020 14:34:59 GMT',
    'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
    server: 'GitHub.com',
    status: '422 Unprocessable Entity',
    'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
    vary: 'Accept-Encoding, Accept, X-Requested-With',
    'x-accepted-oauth-scopes': 'repo',
    'x-content-type-options': 'nosniff',
    'x-frame-options': 'deny',
    'x-github-media-type': 'github.v3; format=json',
    'x-github-request-id': '0407:2B9E:66084C:ACBE5B:5E874993',
    'x-oauth-scopes': 'repo, user',
    'x-ratelimit-limit': '5000',
    'x-ratelimit-remaining': '4951',
    'x-ratelimit-reset': '1585926337',
    'x-xss-protection': '1; mode=block'
  },
  request: {
    method: 'POST',
    url: 'https://api.github.com/repos/bukharim96/blogg-template/git/refs',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'octokit.js/16.43.1 Node.js/12.13.1 (Linux 5.0; x64)',
      authorization: 'token [REDACTED]',
      'content-type': 'application/json; charset=utf-8'
    },
    body: '{"sha":"8aeb1b9edb2ada58723c2da5c63dac854c1cf94c","ref":"refs/heads/master"}',
    request: { hook: [Function: bound bound register] }
  },
  documentation_url: 'https://developer.github.com/v3/git/refs/#create-a-reference'
}
```

Not sure why the ref's not update.

**Comment by gr2m** [comment]
The error is likely coming from this part of the code:

https://github.com/gr2m/octokit-create-pull-request/blob/f139e9919bc0e27669cac2b91fee11777b011398/lib/create-pull-request.js#L103-L108

It means the branch already exists (the `head` parameter). I think we could catch this error and throw an error that is more clear. Would you like to get a PR going for that?

You should be able to resolve the problem by deleting the branch from your repository. You can also set `head` to a name that will change each time, e.g.

```js
  head: `my-branch-${Date.now()}`
```
